[package]
name = "drat"
version = "0.0.1"
authors = ["Xinyun Wu <xin@snaar.net>"]
edition = "2018"
repository = "https://github.com/snaar/drat"

[dependencies]
byteorder = "1"
clap = "2"
csv = "1"
dtoa = "0.4"
flate2 = "1"
lazy_static = "1.2.0"
lzf = "0.3"
reqwest = "0.8"

[lib]
name = "drat_lib"
path = "src/lib.rs"